In [20]:
import numpy as np

In [21]:
# Generamos 24 números (0 al 23) y los organizamos en una matriz de 4 filas x 6 columnas
m = np.arange(24).reshape(4,6)

print("\n--- Acceso a elementos y matriz completa ---")
# Imprime el elemento en la fila con índice 3 y columna con índice 4 (el valor 22)
print("Elemento en la posición m[3,4]:", m[3,4])
print("Matriz completa m:\n", m)


--- Acceso a elementos y matriz completa ---
Elemento en la posición m[3,4]: 22
Matriz completa m:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
# Creamos un arreglo unidimensional con los elementos 2 y 3
m1 = np.array([2,3])

print("\n--- Elevar a potencia con np.power ---")
# np.power(m1, 2) eleva cada elemento del arreglo al cuadrado (2²=4, 3²=9)
print("Resultados al elevar al cuadrado:", np.power(m1,2))


--- Elevar a potencia con np.power ---
Resultados al elevar al cuadrado: [4 9]


In [23]:
# Creamos un arreglo con valores del 2 al 7
m1 = np.array([2,3,4,5,6,7])

print("\n--- Elevar a potencia con el operador ** ---")
# m1**2 eleva cada elemento al cuadrado usando el operador binario de Python
print("Arreglo elevado al cuadrado:\n", np.array(m1**2))


--- Elevar a potencia con el operador ** ---
Arreglo elevado al cuadrado:
 [ 4  9 16 25 36 49]


In [24]:
# Creamos un arreglo con valores del 2 al 7
m1 = np.array([2,3,4,5,6,7])

print("\n--- Obtención del valor mínimo ---")
# m1.min() obtiene el valor más pequeño dentro del arreglo (el valor 2)
print("Valor mínimo en m1:", np.array(m1.min()))


--- Obtención del valor mínimo ---
Valor mínimo en m1: 2


In [25]:
# Definimos dos arreglos unidimensionales
m1 = np.array([2,3,4,5,6,7])
m2 = np.array([11,34,67,99])

print("\n--- Concatenación de arreglos ---")
# np.concatenate((m1, m2)) une ambos arreglos en uno solo de forma secuencial
print("Arreglo concatenado:\n", np.concatenate((m1,m2)))


--- Concatenación de arreglos ---
Arreglo concatenado:
 [ 2  3  4  5  6  7 11 34 67 99]


In [26]:
# Definimos dos matrices de 2x2 para realizar operaciones algebraicas
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

print("\n--- Operaciones con matrices m1 y m2 ---")

# m1 + 2 -> Suma el escalar 2 a cada uno de los elementos de la matriz m1 (broadcasting)
print("Suma de un escalar (m1 + 2):\n", m1 + 2)

# np.multiply(m1, m2) -> Multiplicación elemento a elemento (Producto de Hadamard)
print("\nMultiplicación elemento a elemento (m1 * m2):\n", np.multiply(m1,m2))

# np.dot(m2, m1) -> Producto punto / multiplicación matricial estándar del álgebra lineal
print("\nProducto punto / Multiplicación matricial (np.dot(m2, m1)):\n", np.dot(m2,m1))


--- Operaciones con matrices m1 y m2 ---
Suma de un escalar (m1 + 2):
 [[3 4]
 [5 6]]

Multiplicación elemento a elemento (m1 * m2):
 [[ 5 12]
 [21 32]]

Producto punto / Multiplicación matricial (np.dot(m2, m1)):
 [[23 34]
 [31 46]]
