#CONVERSIÓN DE LISTAS A MATRICES 2D Y USO DE RESHAPE

In [13]:
import numpy as np

### 1. Conversión de una lista simple a un Array 1D


In [14]:
lista_simple = [10, 20, 30, 40, 50]
array_desde_lista = np.array(lista_simple)

print("=== 1. Conversión de Lista Simple a Array 1D ===")
print("Array resultando de la lista:", array_desde_lista)
print("Dimensiones (.ndim):", array_desde_lista.ndim)

=== 1. Conversión de Lista Simple a Array 1D ===
Array resultando de la lista: [10 20 30 40 50]
Dimensiones (.ndim): 1


### 2. Creación de una Matriz 2D a partir de Listas Anidadas

In [15]:
# Cada lista interna representa una fila de la matriz (ej. 3 filas x 3 columnas)
lista_2d = [[1, 2, 3],[4, 5, 6],[7, 8, 9]
]
matriz_2d = np.array(lista_2d)

print("\n=== 2. Matriz 2D creada desde listas anidadas ===")
print(matriz_2d)
print("Forma (.shape):", matriz_2d.shape)
print("Dimensiones (.ndim):", matriz_2d.ndim)


=== 2. Matriz 2D creada desde listas anidadas ===
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma (.shape): (3, 3)
Dimensiones (.ndim): 2


### 3. Generación Rápida de Matrices 2D con np.arange() y .reshape()

In [16]:
# np.arange(20) genera 20 elementos consecutivos (del 0 al 19)
# .reshape(4, 5) reorganiza esos 20 elementos en 4 filas y 5 columnas
matriz_rapida = np.arange(20).reshape(4, 5)

print("\n=== 3. Matriz generada con np.arange(20).reshape(4, 5) ===")
print(matriz_rapida)

# Demostración de la Regla de Reshape: 4 filas x 5 columnas = 20 elementos totales
print("Verificación de dimensión (4 x 5 = 20 elementos):", matriz_rapida.size)


=== 3. Matriz generada con np.arange(20).reshape(4, 5) ===
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Verificación de dimensión (4 x 5 = 20 elementos): 20
